### ISSUE TITLE
Parameter ScheduleExpression is not valid

### ISSUE THREAD

**Issue by animista01** [dvalbuena1/visa_rescheduler_aws#2]
Hey, buen trabajo en esta implementación del visa rescheduler. 

Queria saber si has visto este error?
![image](https://user-images.githubusercontent.com/1688308/215484251-8a4a1ef6-d6c2-4db8-bb61-b154fa02c6a6.png)

**Comment by dvalbuena1** [comment]
Podria adjuntar el archivo `serverless.yml` y `utils.py`

Ya que parese ser un problema al en el `serverless.yml` con el tiempo del evento de EventBridge

Pregunta, ha realizado alguna modificacion adicional al programa?

**Comment by animista01** [comment]
```
org: bryanvillafane
app: visa-rescheduler-lambda
service: visa-rescheduler-lambda

provider:
  name: aws
  logRetentionInDays: 5
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "events:PutRule"
          Resource: "arn:aws:events:*:*:rule/visa-rescheduler-lambda*"

  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  main:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function.
    memorySize: 2048
    image:
      name: img
    events:
      - eventBridge:
          schedule: rate(${file(./json_var.json):retry_value, '10'} minutes)

```

Aca en utils.py, tambien hice modificaciones. Reduje el tiempo en todas las const.
```
from enum import Enum


class Time:
    RETRY_TIME = 60  # wait time between retries/checks for available dates: 1 minute
    EXCEPTION_TIME = 60 * 20  # wait time when an exception occurs: 20 minutes
    COOLDOWN_TIME = 60 * 20  # wait time when temporary banned (empty list): 20 minutes


class Result(Enum):
    SUCCESS = 1
    RETRY = 2
    COOLDOWN = 3
    EXCEPTION = 4
```

Si, hice un par de modificaciones en `visa.py` pero en la logica nada más.
